In [14]:
import pandas as pd
import numpy as np

In [9]:
input_file = "/home/s2208943/ipdis/data/core_data/updated_spreadsheet/CVDclinScores.xlsx"
output_file = "/home/s2208943/ipdis/data/preprocessed_data/Ed_CVD_tabledata/CVD_clinScores_dataset_updated.csv"

In [5]:
df = pd.read_excel(input_file, engine='openpyxl')

In [10]:
df.to_csv(output_file)

In [19]:
df

,ID,sbjGroup,age,sex,diabetes,hypertension,hyperlipidaemia,smoking,SBP,DBP,...,WMH,PVWMH,DWMH,deepAtrophy,supAtrophy,BGPVS,CSPVS,relLes,oldLes,micrBld
0,CVD001,0,76.004929,2,0,0,1.0,0.0,128.666667,76.000000,...,32.848000,2.0,1.0,5.0,5.0,1.0,1.0,NaN,1.0,0.0
1,CVD002,0,77.144031,1,1,1,1.0,0.0,136.000000,64.000000,...,13.424000,2.0,1.0,1.0,2.0,2.0,1.0,NaN,1.0,2.0
2,CVD003,0,92.571194,1,0,1,1.0,1.0,137.500000,59.500000,...,67.456055,3.0,2.0,1.0,1.0,5.0,5.0,NaN,0.0,0.0
3,CVD011,0,72.571194,2,0,1,0.0,0.0,162.333333,81.500000,...,2.576000,1.0,1.0,1.0,1.0,2.0,1.0,NaN,0.0,0.0
4,CVD013,0,77.239869,2,0,0,0.0,0.0,145.000000,84.666667,...,7.032000,1.0,0.0,4.0,4.0,1.0,2.0,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,CVD172,2,66.000000,1,0,1,0.0,2.0,136.000000,82.000000,...,6.035857,1.0,2.0,3.0,3.0,3.0,3.0,NaN,0.0,1.0
246,CVD188,2,78.000000,1,0,1,1.0,0.0,127.000000,57.000000,...,39.932959,3.0,2.0,4.0,4.0,3.0,1.0,NaN,0.0,1.0
247,CVD191,2,71.000000,2,0,1,1.0,0.0,131.000000,70.000000,...,37.185848,3.0,3.0,5.0,5.0,4.0,1.0,NaN,3.0,0.0
248,CVD216,2,71.000000,1,0,1,0.0,1.0,151.000000,68.000000,...,8.534212,1.0,0.0,3.0,3.0,1.0,2.0,0,1.0,0.0
249,CVD238,2,58.000000,1,0,0,1.0,1.0,143.000000,76.000000,...,8.508657,2.0,1.0,1.0,1.0,2.0,3.0,1,0.0,0.0